### ISSUE TITLE
name 'api' is not defined

### ISSUE THREAD

**Issue by ElizaKzi** [Cosmos01/aichat-chatGPT#10]
![image](https://user-images.githubusercontent.com/63360445/207555761-dc9ff502-106d-40e2-8c91-ca26b181d227.png)
![ZN_)Z_K6C2A1E{~EC5I)@%L](https://user-images.githubusercontent.com/63360445/207558859-77bd4682-282c-4f38-8e8e-e246a3677174.png)

虽然常见问题有写重启就行，但是我无论是重启bot还是重启服务器都没用，orz

**Comment by Cosmos01** [comment]
网页上是卡在那个json的页面吗，看看前面加载网页的时候的报错，是不是就打印出json内容，我昨天测试的时候也遇到过一直在那个页面的时候，试了好久才正常，具体也没看，调试的时候又复现不出来了。不知道是他代码逻辑问题还是chatGPT不稳定导致的。

**Comment by Cosmos01** [comment]
测试了一下，如果是重启就可以恢复的话json末尾的error应该为空，如果包含了"error":"RefreshAccessTokenError"，说明你的token有问题

**Comment by ElizaKzi** [comment]
![image](https://user-images.githubusercontent.com/63360445/207576105-3d10ebca-cd03-4883-bd71-fc195bbeb7a4.png)
请问token是在这里获取的吗？
步骤里有一个自动弹出浏览器，不过我这里没有弹出

**Comment by Cosmos01** [comment]
如果一开始就没弹出浏览器那和token关系不大，看看bot初始化过程中的报错情况。
或者你可以试试这个库给的demo能不能正常运行并弹出浏览器：https://github.com/terry3041/pyChatGPT#import-as-a-module 
 
如果按他的要求配置好了也弹不出来，可以去他那提一下issues。

**Comment by ElizaKzi** [comment]
回退了一下浏览器的小版本就可以正常弹出了，看来是依赖库不支持最新版的谷歌浏览器

**Comment by Cosmos01** [comment]
能提供一下版本号参考吗，感谢

**Comment by ElizaKzi** [comment]
![image](https://user-images.githubusercontent.com/63360445/208841915-c7e122de-aa56-47eb-891e-6a6fd6ab7ae6.png)
108.0.5359.99

**Comment by EAloo** [comment]
麻烦能说一下 具体退回到哪个版本了吗 我这里一样的问题

**Comment by Cosmos01** [comment]
> 麻烦能说一下 具体退回到哪个版本了吗 我这里一样的问题

上面不是给了108.0.5359.99，我这用的是最新版，按理说大部分版本都是可以用的，你是不是没有关闭浏览器就启动了
