### ISSUE TITLE
Invalid session token

### ISSUE THREAD

**Issue by sagiriyo** [Cosmos01/aichat-chatGPT#11]
报token无效但是网页倒是弹出来了
可惜啥也没有
![QUC3U7C%{6P}8~ JZ1WG)53](https://user-images.githubusercontent.com/76777320/207583254-8830c851-7c45-413c-8df1-8a641febda37.png)

**Comment by Cosmos01** [comment]
那就是无效。。。直接在这弹出来的浏览器登录一下获取token肯定是可以用的

**Comment by sagiriyo** [comment]
那估计就是抽风了   寄
