### ISSUE TITLE
发生错误: name 'textsplit' is not defined

### ISSUE THREAD

**Issue by Sylphinford** [Cosmos01/aichat-chatGPT#12]
chrome 版本 108.0.5359.125（正式版本） （64 位）

怎么解决

![QQ截图20221214144455](https://user-images.githubusercontent.com/43917892/207611230-32cefe7f-d8c9-4369-8c26-36277f31d0ec.jpg)
![QQ图片20221214145514](https://user-images.githubusercontent.com/43917892/207613583-cb6466c1-e5da-4f01-947f-71c6db7bc23b.png)

**Comment by Cosmos01** [comment]
啊，抱歉，下班前改一半给忘了，重新拉一下吧

**Comment by Sylphinford** [comment]
能用了，谢谢
