### ISSUE TITLE
输入文字可以做个1s左右的延迟，秒输入秒按回车有时候文字会直接消失了，对话框不变

### ISSUE THREAD

**Issue by qq735420530** [Cosmos01/aichat-chatGPT#16]

**Comment by Cosmos01** [comment]
我也出现这种情况了，测试发现延迟也解决不了，输入后就会立刻被清空，我不太懂js，要修复就只能把输入方式改回send_keys了

**Comment by Cosmos01** [comment]
试了一下一只都是这个样子，最好去原作者那里提一下issues，我这只能先换一下输入方式了，等作者修复

**Comment by qq735420530** [comment]
> 

我自己的解决方式是采用循环request，如果这次request时间超过3s以上就取结果
