### ISSUE TITLE
发生错误: list index out of range

### ISSUE THREAD

**Issue by ElizaKzi** [Cosmos01/aichat-chatGPT#18]
![image](https://user-images.githubusercontent.com/63360445/208843304-c9151ecd-9609-48ac-9638-5398695e871a.png)
![image](https://user-images.githubusercontent.com/63360445/208843348-6490c51f-a9eb-42b1-a797-1c652eae6d21.png)
![image](https://user-images.githubusercontent.com/63360445/208843420-16cbf589-9c01-416c-b1b4-0c18a5efeb1f.png)
之前用着好好的，突然就不行了

**Comment by Cosmos01** [comment]
应该是网站更新了吧，等作者pyChatGPT修复或者等我下班再看看

**Comment by Cosmos01** [comment]
知道原因了，已修复：https://github.com/terry3041/pyChatGPT/issues/46
