### ISSUE TITLE
name 'api' is not defined

### ISSUE THREAD

**Issue by Ning-Off** [Cosmos01/aichat-chatGPT#20]
机器人后台面板报错：name 'api' is not defined，开启机器人加载openai页面弹出后很短时间后就关闭。

**Comment by Cosmos01** [comment]
挺久没看了，cf好像又加了一些限制，登录页面要等挺久，我周末有空了更新一下。
如果现在你想用的话，可以在登录页面出来的时候鼠标点击bot的命令行窗口让程序暂停，等过了cf检测在命令行窗口点击回车就可以进入登录步骤了

**Comment by Ning-Off** [comment]
好的，感谢
