### ISSUE TITLE
name 'api' is not defined

### ISSUE THREAD

**Issue by Ning-Off** [Cosmos01/aichat-chatGPT#21]
![image](https://user-images.githubusercontent.com/102615856/217511651-3bd23d40-8979-46ed-86c5-4f10eb9333bc.png)
点击机器人用cmd特性 停止好像也不行，帮助上给的Proxy代理插件下载后还需要自行寻找proxy服务代理商去进行proxy代理配置吗？或者我本地用clash进行本地代理应该也没问题罢（）

**Comment by Cosmos01** [comment]
更新了
那个浏览器插件本来就是让你连本地的这些工具开的端口的

**Comment by Cosmos01** [comment]
你这个问题是浏览器版本，要110以上，你更新一下浏览器就好了
