### ISSUE TITLE
你好，机器人在咨询问题的时候会慢半拍的样子，有时候使用/t查询后，会一直重复上一个咨询的问题（用的新的api接口）

### ISSUE THREAD

**Issue by avadiana** [Cosmos01/aichat-chatGPT#22]
![image](https://user-images.githubusercontent.com/88984346/222874685-76757295-5826-4710-a8f8-7f1e2a77c064.png)

**Comment by avadiana** [comment]
会不会是单词回复的token字数的限制，所以分两次回答了？

**Comment by avadiana** [comment]
![image](https://user-images.githubusercontent.com/88984346/222875477-fb79c1eb-aaf8-47e9-8cdd-f89abaa00ec7.png)

**Comment by Cosmos01** [comment]
逻辑问题，已修复。感谢提醒，昨天通宵写的头昏脑胀，把发送信息和增加信息字段的顺序搞反了
