### ISSUE TITLE
发生错误: Error communicating with OpenAI

### ISSUE THREAD

**Issue by plumephoenix** [Cosmos01/aichat-chatGPT#23]
发送消息就回复这个，控制台没报错，刚弄的openai新号
看openai的Usage是已经产生计费了
是openai账号的问题吗？

**Comment by plumephoenix** [comment]
> 发送消息就回复这个，控制台没报错，刚弄的openai新号 看openai的Usage是已经产生计费了 是openai账号的问题吗？

bot是部署在腾讯云服务器上

**Comment by Nsekri** [comment]
我也一直这个错误，用clash给控制台代理还是不行

**Comment by Cosmos01** [comment]
代理问题，我增加了代理配置项，可以试试看。如果还不行就切一下节点。

**Comment by plumephoenix** [comment]
> 我也一直这个错误，用clash给控制台代理还是不行

麻烦问一下你有解决吗，我试了作者说的还是不行

**Comment by Nsekri** [comment]
> 

已经解决了，可能你代理那里端口和配置的不一样？或者换个街道

**Comment by plumephoenix** [comment]
> > 
> 
> 已经解决了，可能你代理那里端口和配置的不一样？或者换个街道

谢谢，想再问一下你是在本地还是云服务器上面弄的，如果是云服务器的话可以用clash吗？（或者有什么风险吗？）

**Comment by Cosmos01** [comment]
> > > 
> > 
> > 
> > 已经解决了，可能你代理那里端口和配置的不一样？或者换个街道
> 
> 谢谢，想再问一下你是在本地还是云服务器上面弄的，如果是云服务器的话可以用clash吗？（或者有什么风险吗？）

可以用，注意端口别对外开放就行

**Comment by plumephoenix** [comment]
> > > > 
> > > 
> > > 
> > > 已经解决了，可能你代理那里端口和配置的不一样？或者换个街道
> > 
> > 
> > 谢谢，想再问一下你是在本地还是云服务器上面弄的，如果是云服务器的话可以用clash吗？（或者有什么风险吗？）
> 
> 可以用，注意端口别对外开放就行

好哒好哒，感谢！我再去研究一下
