### ISSUE TITLE
发生错误: This model's maximum context length is 4096 tokens. However, you requested 4130 tokens (34 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.

### ISSUE THREAD

**Issue by Nsekri** [Cosmos01/aichat-chatGPT#24]
![image](https://user-images.githubusercontent.com/64681506/222957614-895e8f5e-a1bc-4d94-9785-5097322571c8.png)
回答了几次后就这样了，无论重置还是切换新的依旧这样提示

**Comment by Cosmos01** [comment]
是最新的代码吗
还有预设值是什么，换成项目里的default也是这样吗？

**Comment by Nsekri** [comment]
> 是最新的代码吗 还有预设值是什么，更换项目目录里的默认也是这样吗？

是的，使用的默认的default。尝试切换另一个预设和创建新的依旧这样提示

**Comment by Cosmos01** [comment]
复现不出你这个问题，我无能为力了。
能否看看conversations.json文件，会话保存在里面。或者你直接删了重新获取一个

**Comment by Nsekri** [comment]
> 复现不出你这个问题，我无能为力了。 能否看看conversations.json文件，会话保存在里面。或者你直接删了重新获取一个
我覆盖掉了。。。不知道是不是因为其他群让他续写了几次故事导致的

**Comment by Cosmos01** [comment]
主要是重置会话没有生效的问题，这个我也不知道为什么，我这测试重置会话都是正常的。
至于会话过长问题我已经加了拒绝方案，过长时会自动删除最早两条对话，可以更新一下代码。
