### ISSUE TITLE
'ServiceFunc' object is not iterable

### ISSUE THREAD

**Issue by Gilgaladly** [Cosmos01/aichat-chatGPT#26]
hoshino/tool.py", line 27, in not_conflict
    service_funcs.extend(t.find_handler(event))
TypeError: 'ServiceFunc' object is not iterable

这个是闲聊插件与hoshino版本不匹配吗

**Comment by Cosmos01** [comment]
不太清楚，你hoshino用的不是最新版本吗

**Comment by Gilgaladly** [comment]
> 不太清楚，你hoshino用的不是最新版本
https://github.com/Ice-Cirno/HoshinoBot  咖啡佬的hoshino应该很久没更新了哇

**Comment by Cosmos01** [comment]
对啊，我用的就是最后的版本，hoshino/tool.py是啥，没看到有这个文件，你是魔改过吗。。

**Comment by Cosmos01** [comment]
看报错你可以试着把几个多触发条件的功能的元组都改成单个字符串，说不定就可以运行了。
比如：@sv.on_fullmatch(('查询人格', '获取人格', '人格列表', '会话列表', '获取会话', '查询会话'))
改成：@sv.on_fullmatch('查询人格')
