### ISSUE TITLE
人格无法修改

### ISSUE THREAD

**Issue by Fhm-newbie** [Cosmos01/aichat-chatGPT#28]
![图片](https://user-images.githubusercontent.com/63446200/225636376-363e4ead-ea61-4acb-8cbc-2e48077a9f13.png)
大佬您好，我设置了一个人格之后我想对这个人格进行修改，但是很显然它并没有成功修改人格。。。我也进行过重置人格的操作，但是也没有用，能请问一下是不是我操作有问题吗？

**Comment by Fhm-newbie** [comment]
还有就是能增加一个删除人格的操作吗？有几个没设置好的人格在人格列表里占着有点麻烦

**Comment by Cosmos01** [comment]
晓得问题了，改完之后你要切换才会生效，我之后改一下逻辑吧，删除可以加，明早一起处理

**Comment by Fhm-newbie** [comment]
好的，大佬辛苦了

**Comment by Cosmos01** [comment]
已更新

**Comment by Fhm-newbie** [comment]
好的，感谢大佬
