### ISSUE TITLE
发生错误: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by a7236723** [Cosmos01/aichat-chatGPT#3]
[2022-12-11 11:56:30,985 人工智障] INFO: Message 1495289549 triggered init_neko.
/root/HoshinoBot/hoshino/modules/aichat-chatGPT/aichat.py:63: RuntimeWarning: coroutine 'AsyncChatbot.get_chat_response' was never awaited
  return f"发生错误: {str(e)}"
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

后台显示如上，QQ回复如标题。

**Comment by Cosmos01** [comment]
抱歉，我重新装了一遍，也并没有复现出这个问题。我也不太清楚是什么情况

**Comment by LDsylsp** [comment]
我也碰上这个问题了，不知道怎么解决orz

**Comment by Cosmos01** [comment]
知道原因了，新版本revChatGPT不兼容，执行一下pip install revChatGPT==0.0.35

**Comment by Cosmos01** [comment]
他今天刚刚更新的，绝了

**Comment by Cosmos01** [comment]
> 我也碰到这个问题了，不知道怎么解决orz

pip install revChatGPT==0.0.35

**Comment by LDsylsp** [comment]
成功了，感谢大佬
