### ISSUE TITLE
发生错误: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by qwe3107231** [Cosmos01/aichat-chatGPT#33]
windows10
go-cqhttp v1.0.0-rc5
hoshinobot
![QQ截图20230423002024](https://user-images.githubusercontent.com/73685785/233795558-583102ab-b258-4cbb-a09c-9a5b844165dc.png)
网页端也正常打印结果，插件这边报错。

**Comment by Cosmos01** [comment]
可以看看后台具体的报错信息吗

**Comment by qwe3107231** [comment]
![3)F_ $Y%%2O82LDFXG~Y 9W](https://user-images.githubusercontent.com/73685785/233819159-cf3df6ad-49d1-4eba-ac6e-9a0d6acffebd.png)
![9G_3Y MBM6K{S)54Q1DFY)P](https://user-images.githubusercontent.com/73685785/233819161-e937af3e-8350-40ed-bc64-d53742f35b75.png)
![J4M1}OD}_`HW4XA6@RZ5(WB](https://user-images.githubusercontent.com/73685785/233819162-685ef5d8-af32-49d2-9ab6-f07c61fe5d90.png)

**Comment by Cosmos01** [comment]
这问题我实在想不通，试了几种情况也没复现出来，代码里也没有用到"group"这个属性。
你确认几个情况：
1.是否有其他ai对话插件
2.用@机器人代替/t是否也会报错
3.安装openai库版本是0.27.0（pip install openai==0.27.0）
4.确认一下config.ini配置有没有做不必要修改(只改api_key和代理)，并且是否是utf-8保存

**Comment by qwe3107231** [comment]
我使用的是网页版分支

**Comment by Cosmos01** [comment]
抱歉，网页版作者不维护了，我也没时间修问题，api版本方便不少，建议还是用api

**Comment by Cosmos01** [comment]
因为openai一直在改网页，得一直跟着变，太麻烦了
