### ISSUE TITLE
插件显示import failed

### ISSUE THREAD

**Issue by Fhm-newbie** [Cosmos01/aichat-chatGPT#4]
大佬您好，我安装了插件并pip了第三方库之后，重新启动bot显示import failed，最初的提示原因是name json not defined
![image](https://user-images.githubusercontent.com/63446200/206907922-98a31fde-aed8-421e-a854-83014f73940a.png)
于是我就在ai_chat.py里加了import json，然后就报错如下
![image](https://user-images.githubusercontent.com/63446200/206907841-4f8d09a2-9c91-40da-a2d8-2e8997f3df42.png)
能请问一下您的看法吗？实在不知道为什么不能用了。。。

**Comment by Cosmos01** [comment]
后面这个报错是revChatGPT的问题，参考https://github.com/acheong08/ChatGPT/issues/213

**Comment by Cosmos01** [comment]
这应该是网站加了验证码，暂时确实无法解决，我目前也没遇到这情况，可以尝试使用第二个认证方法，用token来认证。

**Comment by Fhm-newbie** [comment]
好的，我试一下

**Comment by Cosmos01** [comment]
参考：https://github.com/acheong08/ChatGPT/wiki/Setup#session-token-authentication

**Comment by Fhm-newbie** [comment]
它确实有反应了。。。
但是回复发生错误: asyncio.run() cannot be called from a running event loop
![image](https://user-images.githubusercontent.com/63446200/206909155-a57490b6-b5a7-4fba-b9a4-41acf4b7e45c.png)

**Comment by Fhm-newbie** [comment]
![image](https://user-images.githubusercontent.com/63446200/206909197-cd8777f7-eb2e-4719-bf9f-b5fb8e1ea809.png)
日志里这段我不知道有没有关系

**Comment by Cosmos01** [comment]
草，原来是revChatGPT版本原因，我用的是昨天的版本，回退一下吧，pip install revChatGPT==0.0.35

**Comment by Fhm-newbie** [comment]
好了，大佬辛苦了

**Comment by Cosmos01** [comment]
感谢
