### ISSUE TITLE
插件显示import failed

### ISSUE THREAD

**Issue by Felix010525** [Cosmos01/aichat-chatGPT#5]
麻烦佬帮我看一下报错，十分感谢！！

![JY6$6F`ULXP93W}3IR_(_(E](https://user-images.githubusercontent.com/115688756/206913640-c5dba59b-a07c-47b7-82e6-dc358ef7321b.png)

![@83@WQFII~`YJ8{D}0L9U%W](https://user-images.githubusercontent.com/115688756/206913610-a361f444-e3ce-4f94-b731-f374bceb12a5.png)

跟朋友研究了半天，尝试了重新安装也没整出个所以然来，麻烦佬了Orz

**Comment by Cosmos01** [comment]
你认证方式是什么样的，怎么写的？（具体密码记得打码）

**Comment by Felix010525** [comment]
认证方式是用的邮箱和密码，具体是在auth里输的邮箱账密，邮箱之前注册过了

**Comment by Cosmos01** [comment]
这应该是OpenAIAuth，就是revChatGPT认证模块报错，你试试换成access_token认证看看

**Comment by Felix010525** [comment]
佬这个token应该写到哪里

**Comment by GaryDu0123** [comment]
https://github.com/acheong08/ChatGPT/issues/251
好像是关闭了auth

**Comment by Cosmos01** [comment]
参考：https://github.com/acheong08/ChatGPT/wiki/Setup
auth.json中填写：
{
    "session_token": "<YOUR_TOKEN>"
}

**Comment by Cosmos01** [comment]
不能登录就手动登录然后填写session_token应该是可以用的

**Comment by Felix010525** [comment]
用token成了！谢谢佬
