### ISSUE TITLE
发生错误: descriptor 'get_coro' for '_asyncio.Task' objects doesn't apply to a 'Task' object

### ISSUE THREAD

**Issue by Sylphinford** [Cosmos01/aichat-chatGPT#7]
nest_asyncio 1.5.6
revChatGPT 0.0.38.8

海外直连

![QQ截图20221212152456](https://user-images.githubusercontent.com/43917892/207071303-a0947eae-4e32-408c-a35a-8ac8c5a20ddf.jpg)

chrome浏览器在和BOT同个电脑上 获取的TOKEN
浏览器能正常对话
在QQ里就回复错误
怎么解？

**Comment by Cosmos01** [comment]
不太清楚，我已经访问不了chatGPT了，显示满负荷炸了

**Comment by Cosmos01** [comment]
可能是nest_asyncio和别的什么东西冲突了

**Comment by Cosmos01** [comment]
我看到新版本的revChatGPT引入了报错处理，也使用了nest_asyncio，你可以尝试把nest_asyncio的两行代码删除试试

**Comment by Cosmos01** [comment]
我这边怎么都连不上，暂时处理不了

**Comment by Cosmos01** [comment]
https://github.com/acheong08/ChatGPT/blob/main/src/revChatGPT/revChatGPT.py#L549
删除aichat.py里的这两行：
import nest_asyncio
nest_asyncio.apply()

**Comment by Sylphinford** [comment]
删了还是一样的错误消息

**Comment by Cosmos01** [comment]
如果删了也这样，也许是其他插件冲突导致的。
你现在能打得开chatGPT吗，我这换了好几个代理也打不开。

**Comment by Sylphinford** [comment]
浏览器上能正常使用

**Comment by Cosmos01** [comment]
网络恢复了，我更新了revChatGPT 0.0.38.8测试了一下，没复现出这种情况。

**Comment by Cosmos01** [comment]
转到另一个方案了，原方案暂时弃用，你可以试试新方案。先close了
