### ISSUE TITLE
Windows服务器是不是用不了？

### ISSUE THREAD

**Issue by Sasa-kid** [Cosmos01/aichat-chatGPT#8]
我发启用命令有反应，其他命令一点反应都没有，连报错都没有，参数也按要求填了
![image](https://user-images.githubusercontent.com/68634616/207125551-9efc1b85-dec1-4c4e-90a7-c48353cacdf4.png)
后台也没有报错
![image](https://user-images.githubusercontent.com/68634616/207125301-9d2ec6e8-722c-494c-a27e-ee341614f291.png)

**Comment by Cosmos01** [comment]
@bot发送消息有回复吗，控制台要是连init_neko之类的函数名都没打印出来说明你加载插件的时候就出错了，可以往前看看控制台

**Comment by Sasa-kid** [comment]
> @bot发送消息有回复吗，控制台要是连init_neko之类的函数名都没打印出来说明你加载插件的时候就出错了，可以往前看看控制台

发现报错了
![image](https://user-images.githubusercontent.com/68634616/207132918-0d56435a-c01d-49ce-bbe0-534792eed58c.png)

**Comment by Cosmos01** [comment]
这个报错我在常见问题里写了，请确保填写的参数无误。
主要是保证你获取参数的时候的ip和你bot的ip一致，你是Windows部署的话直接在部署的机器上打开浏览器获取参数就行了，如果有代理记得和bot用相同代理。

**Comment by Sasa-kid** [comment]
> 这个报错我在常见问题里写了，请确保填写的参数无误。 主要是保证你获取参数的时候的ip和你bot的ip一致，你是Windows部署的话直接在部署的机器上打开浏览器获取参数就行了，如果有代理记得和bot用相同代理。

好的，感谢，我换了一个代理程序就可以用了
