### ISSUE TITLE
TypeError: expected str,bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Agnes4m** [Cosmos01/aichat-chatGPT#9]
window端启动报错，然后情况就是lssv里显示了人工智障，除此以外其他功能都用不了。
另外希望可以加个前缀识别，比如chat这种
![image](https://user-images.githubusercontent.com/70925546/207210486-1a9984b5-b803-4fc9-8b7e-13f6bc1b291b.png)

**Comment by Cosmos01** [comment]
读目录报错吧，如果你没动过两个json文件，你可以试试把CONFIG_PATH = os.path.dirname(__file__)直接写成插件的目录CONFIG_PATH = "C:\......\aichat-chatGPT\"

**Comment by Cosmos01** [comment]
前缀的命令可以加，晚点有空了加上

**Comment by Agnes4m** [comment]
还是出错了
![image](https://user-images.githubusercontent.com/70925546/207221898-0f743ea7-068a-4e6a-bb32-fbf8b38792bf.png)

**Comment by Cosmos01** [comment]
你这个x08...，你输入反斜杠的时候要再加个反斜杠转义:"C:\\\bot...\\\aichat-chatGPT"

**Comment by Agnes4m** [comment]
两个的话和一开始的报错又一样了
![image](https://user-images.githubusercontent.com/70925546/207222979-427ec031-b82c-4e7c-bcda-f8dd1e948eca.png)

**Comment by Cosmos01** [comment]
抱歉，最早在开会没看太仔细，我看你报错里的代码好像是0.0.38.8以上版本的revChatGPT？目前我只测试到0.0.38.8，如果你用的是高版本就回退一下吧：pip3 install revChatGPT==0.0.38.8

**Comment by Agnes4m** [comment]
没有报错了，还有一个问题就是怎么使用，`启用 人工智障`后直接发消息，或者艾特发消息都没有反应

**Comment by Cosmos01** [comment]
看看是不是和这个一样：https://github.com/Cosmos01/aichat-chatGPT/issues/8

**Comment by Agnes4m** [comment]
设置过了，但我完全不知道指令是什么，是直接群里发送任意消息都回复？还是需要艾特？
![image](https://user-images.githubusercontent.com/70925546/207240333-897c69f6-e116-498d-b7d8-186223b2f127.png)

**Comment by Cosmos01** [comment]
我看了一下，可能是因为chatGPT又开始搞事了，暂时可能用不了了，等revChatGPT更新吧，参考：https://github.com/acheong08/ChatGPT/issues/261

**Comment by Cosmos01** [comment]
回复是和原插件一样的，设置概率回复或直接@他加上内容，晚点我下班了要是能用了会加一下命令前缀方式

**Comment by Cosmos01** [comment]
转到另一个方案了，这个暂时弃用，你是Windows的可以试试。我先Close了
